site_name: ZooBerry Docs
site_url: https://docs.zooberry.org/
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep_orange
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.footnote.tooltips
    # - search.highlight
nav:
  - Home: 
    - index.md
    - Attributions: attributions.md
  - Reference:
    - Zoo Tycoon 1:
        - File Formats: zt1/file-formats.md
        - Scenery Configuration: zt1/Reference/scenery-files.md
        - Scenario Configuration: zt1/Reference/scenario-files.md
        - Entity IDs: zt1/Reference/entity-ids.md
        - Mod Installation: zt1/Reference/mod-installation.md
  - EMU API:
      - Getting Started: emu/getting-started.md
      - EMU Command Console: emu/emu-console.md
      - Lua Scripts: emu/emu-scripts.md
  - PANDA Loader:
      - Getting Started: panda/getting_started.md

extra:
  social:
    - icon: material/github
      link: https://github.com/GoosiferIO/ZooBerry-Docs
  generator: false
copyright: Copyright &copy; 2024 Goosifer.IO
repo_url: https://github.com/GoosiferIO/ZooBerry-Docs
repo_name: GoosiferIO/ZooBerry-Docs
edit_uri: edit/main/docs/
plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - git-committers:
      repository: GoosiferIO/ZooBerry-Docs
      branch: main
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
