site_name: ZooBerry Docs
site_url: https://docs.zooberry.org/
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep_orange
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    # - navigation.tabs.sticky
    # - navigation.expand
    - navigation.indexes
    - navigation.path
    - toc.follow
    # - toc.integrate
    - navigation.top
    - search.suggest
    - navigation.footer
    - content.action.edit
    - content.action.view
    - content.footnote.tooltips
    - content.tabs
    # - search.highlight
nav:
  - Home:
      - Index: index.md
  - Modding Tutorials:
    - Getting Started: 
        - zt1/getting-started/index.md
        - File Formats and Tools: zt1/getting-started/file-formats-and-tools.md
        - Mod Installation: zt1/getting-started/mod-installation.md
  - Reference:
      - Configuration References:
          - zt1/configuration-references/index.md
          - Scenery : zt1/configuration-references/scenery-files.md
          - Scenarios : zt1/configuration-references/scenario-files.md
      - String Table References:
          - Notable String IDs: zt1/string-tables/entity-ids.md
          - Official String Tables:
              - lang0: zt1/string-tables/official/lang0.md
              - lang001: zt1/string-tables/official/lang001.md
              - lang002: zt1/string-tables/official/lang002.md
              - lang007: zt1/string-tables/official/lang007.md
              - lang008: zt1/string-tables/official/lang008.md
              - lang009: zt1/string-tables/official/lang009.md
              - lang010: zt1/string-tables/official/lang010.md
              - lang012: zt1/string-tables/official/lang012.md
              - lang013: zt1/string-tables/official/lang013.md
              - lang015: zt1/string-tables/official/lang015.md
              - lang016: zt1/string-tables/official/lang016.md
              - lang017: zt1/string-tables/official/lang017.md
              - lang018: zt1/string-tables/official/lang018.md
              - lang019: zt1/string-tables/official/lang019.md
              - lang020: zt1/string-tables/official/lang020.md
              - lang021: zt1/string-tables/official/lang021.md
              - lang100: zt1/string-tables/official/lang100.md
              - lang200: zt1/string-tables/official/lang200.md
              - lang300: zt1/string-tables/official/lang300.md
          - Unofficial String Tables:
              - LANG--ZTCDD: zt1/string-tables/unofficial/LANG--ZTCDD.md
              - LANG--ZooTek: zt1/string-tables/unofficial/LANG--ZooTek.md
              - LANG--ZKL: zt1/string-tables/unofficial/LANG--ZKL.md
              - LANG--ZBorsato: zt1/string-tables/unofficial/LANG--ZBorsato.md
              - LANG--Jane: zt1/string-tables/unofficial/LANG--Jane.md
              - LANG--JBL: zt1/string-tables/unofficial/LANG--JBL.md
              - LANG--fern-Tek: zt1/string-tables/unofficial/LANG--fern-tek.md
              - langZA01: zt1/string-tables/unofficial/langZA01.md
              - langZA02: zt1/string-tables/unofficial/langZA02.md
              - langZA03: zt1/string-tables/unofficial/langZA03.md
              - lang--TKZTUFcombin.md: zt1/string-tables/unofficial/lang--TKZTUFcombin.md
  - Web Resources: zt1/getting-started/web-resources.md
  - Attributions: attributions.md

  # - 'EMU API':
  #     - 'Getting Started': 'emu/getting-started.md'
  #     - 'EMU Command Console': 'emu/emu-console.md'
  #     - 'Lua Scripts': 'emu/emu-scripts.md'
  # - 'PANDA Loader':
  #     - 'Getting Started': 'panda/getting_started.md'
extra:
  social:
    - icon: material/github
      link: https://github.com/GoosiferIO/ZooBerry-Docs
  generator: false
copyright: Copyright &copy; 2024 Goosifer.IO
repo_url: https://github.com/GoosiferIO/ZooBerry-Docs
repo_name: GoosiferIO/ZooBerry-Docs
edit_uri: edit/main/docs/
plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - git-committers:
      repository: GoosiferIO/ZooBerry-Docs
      branch: main
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
